### ISSUE TITLE
Get not found error

### ISSUE THREAD

**Issue by ledinhtuyenbkdn** [okteto/pipeline#21]
Hi sir, I'm getting an error when trigger pipeline. I checked my namespace on Okteto web, it is successfully deployed but I still got error.

Console output:
```
Deploying repository 'deploy_from_github_actions'...
Waiting for repository 'deploy_from_github_actions' to be deployed...
 x  Not found
```

And my workflow:
```
steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      - name: Activate Namespace
        uses: okteto/namespace@latest
        with:
          name: ${{env.NAMESPACE}}
      - name: Trigger the pipeline
        uses: okteto/pipeline@main
        with:
          name: deploy_from_github_actions
          namespace: ${{env.NAMESPACE}}
          timeout: 8m
          skipIfExists: false
```
